In [ ]:
%matplotlib inline



Tensors
==========================

Tensors are a specialized data structure that are very similar to arrays and matrices.
In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to `NumPy’s ndarrays, except that **tensors can run on GPUs or other hardware accelerators.** 

- tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see `bridge-to-np-label`). 
- Tensors
are also optimized for automatic differentiation. Which is critical for deep learning!

![picture](https://drive.google.com/uc?id=1inz8rB_q_mGuSsYz5dRl4C9-9qLTg5Xm)

In [2]:
import torch
import numpy as np

## Initializing a Tensor

Tensors can be initialized in various ways. Take a look at the following examples:

**Directly from data**

Tensors can be created directly from data. The data type is automatically inferred.



In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa).

This becomes handy when you would want to pre-process on NumPy using many of Numpy functions and convert to Tensor for GPU advantageous functions.
Same goes for post-processing! (converting Tensor to NumPy)


In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]])


**From another tensor creating operation:**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.



In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

x_zeros = torch.zeros_like(x_data)
print(f"Zeros Tensor: \n {x_zeros} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8346, 0.6601],
        [0.7714, 0.1391]]) 

Zeros Tensor: 
 tensor([[0, 0],
        [0, 0]]) 



**With random or constant values:**

``shape`` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8970, 0.2701, 0.2081],
        [0.9302, 0.1464, 0.6771]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

Tensor attributes describe their **shape, datatype, and the device** on which they are stored.



In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing,
indexing, slicing), sampling and more are
comprehensively described [here](https://pytorch.org/docs/stable/torch.html).

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU!). 

If you’re using Colab, allocate a GPU by going to `Runtime > Change runtime type > GPU`.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using
``.to`` method (after checking for GPU availability). Keep in mind that copying large tensors
across devices can be expensive in terms of time and memory!



In [9]:
tensor = torch.rand(3,4) # re-init random tensor
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


Try out some of the operations from the list.
If you're familiar with the NumPy API, you'll find the Tensor API a breeze to use.




**Standard numpy-like indexing and slicing:**



In [11]:
tensor = torch.ones(3, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
print(f"Last column: {tensor[:, -1]}")

# remember [row x column]. So select all rows in selected 1 column and set it to 0.
tensor[:,1] = 0 
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1.])
Last column: tensor([1., 1., 1.])
Last column: tensor([1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors** You can use ``torch.cat`` to concatenate a sequence of tensors along a given dimension.
See also [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html)
another tensor joining op that is subtly different from ``torch.cat``.



In [19]:
print(tensor.shape)
print(tensor.T.shape)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(t1.shape)

torch.Size([3, 4])
torch.Size([4, 3])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([3, 12])


**Arithmetic operations**



In [20]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

print(y1)

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: UserWarning: An output with one or more elements was resized since it had shape [3, 4], which does not match the required output shape [3, 3].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:23.)
  


**Single-element tensors** If you have a one-element tensor, for example by aggregating all
values of a tensor into one value, you can convert it to a Python
numerical value using ``item()``:



In [22]:
agg = tensor.sum()
agg_item = agg.item()
print(agg)
print(agg_item, type(agg_item))

tensor(9.)
9.0 <class 'float'>


**In-place operations**
Operations that store the result into the operand are called in-place. 

Normally, python will copy and create new memory for new variables, using an in-place operation, no new memory will be used.
They are denoted by a ``_`` suffix.

For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.



In [23]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


**Note** In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.




## Bridge with NumPy
Tensors on the CPU and NumPy arrays can *__share__ their underlying memory
locations*, and changing one will change	the other.



Tensor to NumPy array


In [24]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor is also reflected in the NumPy array. (because they share the memory)



In [25]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.



In [26]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


## Quiz


1. Create a random tensor called `rand_tensor`, tensor of all 1s called `one_tensor`, tensor of all 0s called `zero_tensor` ALL of size `3 x 4`, and print the tensors, and print its attributes (recall: device, datatype, shape). If the tensor is on CPU, place it on GPU!

2. create a numpy array of all 1s of size `3 x 4`. Convert them to pytorch Tensors, print the tensors & its attributes. Again if the tensor is on CPU, place it on GPU!

3. We are going to do matrix multiplication. Create a Tensor that is able to multiply to our `one_tensor` created above, and perform the matrix multiplication.

4. Create a Tensor to "concatenate" to the row (first dimension) of our `zero_tensor` above. Create another Tensor to "stack" on `dim=0` to our `zero_tensor` as well. Print the shapes of all created tensors. 

5. Create a tensor of size (3,4) and [reshape](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) it to (6,2). Print the resulting shape of the tensor.

6. Create a linearly interpolation of $x$ values where $0 <= x <= 10$ evenly spaced by 2. (Hint: [linspace](https://pytorch.org/docs/stable/generated/torch.linspace.html#torch.linspace))