In [ ]:
%matplotlib inline



Tensors
==========================

Tensors are a specialized data structure that are very similar to arrays and matrices.
In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to `NumPy’s ndarrays, except that **tensors can run on GPUs or other hardware accelerators.** 

- tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see `bridge-to-np-label`). 
- Tensors
are also optimized for automatic differentiation. Which is critical for deep learning!

![picture](https://drive.google.com/uc?id=1inz8rB_q_mGuSsYz5dRl4C9-9qLTg5Xm)

In [1]:
import torch
import numpy as np

## Initializing a Tensor

Tensors can be initialized in various ways. Take a look at the following examples:

**Directly from data**

Tensors can be created directly from data. The data type is automatically inferred.



In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa).

This becomes handy when you would want to pre-process on NumPy using many of Numpy functions and convert to Tensor for GPU advantageous functions.
Same goes for post-processing! (converting Tensor to NumPy)


In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**From another tensor creating operation:**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.



In [ ]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2621, 0.5799],
        [0.6417, 0.2297]]) 



**With random or constant values:**

``shape`` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.



In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4701, 0.6289, 0.6239],
        [0.5850, 0.3134, 0.1547]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Attributes of a Tensor

Tensor attributes describe their **shape, datatype, and the device** on which they are stored.



In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing,
indexing, slicing), sampling and more are
comprehensively described [here](https://pytorch.org/docs/stable/torch.html).

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU!). 

If you’re using Colab, allocate a GPU by going to `Runtime > Change runtime type > GPU`.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using
``.to`` method (after checking for GPU availability). Keep in mind that copying large tensors
across devices can be expensive in terms of time and memory!



In [ ]:
tensor = torch.rand(3,4) # re-init random tensor
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


Try out some of the operations from the list.
If you're familiar with the NumPy API, you'll find the Tensor API a breeze to use.




**Standard numpy-like indexing and slicing:**



In [ ]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

# remember [row x column]. So select all rows in selected 1 column and set it to 0.
tensor[:,1] = 0 
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**Joining tensors** You can use ``torch.cat`` to concatenate a sequence of tensors along a given dimension.
See also [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html)
another tensor joining op that is subtly different from ``torch.cat``.



In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**Arithmetic operations**



In [ ]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**Single-element tensors** If you have a one-element tensor, for example by aggregating all
values of a tensor into one value, you can convert it to a Python
numerical value using ``item()``:



In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**In-place operations**
Operations that store the result into the operand are called in-place. 

Normally, python will copy and create new memory for new variables, using an in-place operation, no new memory will be used.
They are denoted by a ``_`` suffix.

For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.



In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


**Note** In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.




## Bridge with NumPy
Tensors on the CPU and NumPy arrays can *__share__ their underlying memory
locations*, and changing one will change	the other.



Tensor to NumPy array


In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor is also reflected in the NumPy array. (because they share the memory)



In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.



In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


## Quiz


1. Create a random tensor called `rand_tensor`, tensor of all 1s called `one_tensor`, tensor of all 0s called `zero_tensor` ALL of size `3 x 4`, and print the tensors, and print its attributes (recall: device, datatype, shape). If the tensor is on CPU, place it on GPU!

In [2]:
rand_tensor = torch.rand(3,4)
one_tensor = torch.ones(3,4)
zero_tensor = torch.zeros(3,4)

print(rand_tensor)
print(one_tensor)
print(zero_tensor)
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Device tensor is stored on: {rand_tensor.device}")
if torch.cuda.is_available():
    gpu_rand_tensor = rand_tensor.to("cuda")
print(f"Device tensor is stored on: {gpu_rand_tensor.device}")


tensor([[0.8558, 0.8993, 0.7481, 0.1362],
        [0.5445, 0.6361, 0.1251, 0.2134],
        [0.8967, 0.0248, 0.8069, 0.2765]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


NameError: ignored

2. create a numpy array of all 1s of size `3 x 4`. Convert them to pytorch Tensors, print the tensors & its attributes. Again if the tensor is on CPU, place it on GPU!

In [ ]:
one_numpy = np.ones((3,4))
one_tensor = torch.from_numpy(one_numpy)
print(one_tensor)
print(f"Shape of tensor: {one_tensor.shape}")
print(f"Datatype of tensor: {one_tensor.dtype}")
print(f"Device tensor is stored on: {one_tensor.device}")
if torch.cuda.is_available():
    gpu_one_tensor = one_tensor.to("cuda")
print(f"Device tensor is stored on: {gpu_one_tensor.device}")


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float64
Device tensor is stored on: cpu
Device tensor is stored on: cuda:0


3. We are going to do matrix multiplication. Create a Tensor that is able to multiply to our `one_tensor` created above, and perform the matrix multiplication.

In [ ]:
one_tensor.shape
tmp_tensor = torch.ones(4,3, dtype=torch.double)
matmuled = one_tensor @ tmp_tensor
print(f"Matrix multiplied tensor shape: {matmuled.shape}")
print(matmuled)

Matrix multiplied tensor shape: torch.Size([3, 3])
tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]], dtype=torch.float64)


4. Create a Tensor to "concatenate" to the row (first dimension) of our `zero_tensor` above. Create another Tensor to "stack" on `dim=0` to our `zero_tensor` as well. Print the shapes of all created tensors. 

In [5]:
zero_tensor = torch.zeros(3,4)
print(zero_tensor.shape)
concat_tensor = torch.ones(3,4)
concatted = torch.concat((zero_tensor, concat_tensor), dim=0)
print(f'Concatted tensor is now of shape: {concatted.shape}')

stacked = torch.stack((concat_tensor, zero_tensor), dim=0)
print(f'Stacked tensor is now of shape: {stacked.shape}')

torch.Size([3, 4])
Concatted tensor is now of shape: torch.Size([6, 4])
Stacked tensor is now of shape: torch.Size([2, 3, 4])


5. Create a tensor of size (3,4) and [reshape](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) it to (6,2). Print the resulting shape of the tensor.

In [8]:
rand_tensor = torch.rand(3,4)
reshaped = rand_tensor.reshape(6,2)
print(rand_tensor)
print(reshaped)
print(reshaped.shape)

tensor([[0.5886, 0.0751, 0.4077, 0.5222],
        [0.5586, 0.0508, 0.0102, 0.4679],
        [0.6507, 0.2190, 0.5530, 0.0624]])
tensor([[0.5886, 0.0751],
        [0.4077, 0.5222],
        [0.5586, 0.0508],
        [0.0102, 0.4679],
        [0.6507, 0.2190],
        [0.5530, 0.0624]])
torch.Size([6, 2])


6. Create a linear interpolation of $x$ values where $0 <= x <= 10$ evenly spaced by 2. (Hint: [linspace](https://pytorch.org/docs/stable/generated/torch.linspace.html#torch.linspace))

In [12]:
print(torch.linspace(0,10,6))
# print(torch.lerp(torch.tensor(0, dtype=torch.float), torch.tensor(10, dtype=torch.float), 2))

tensor([ 0.,  2.,  4.,  6.,  8., 10.])
